on: [push, pull_request, workflow_dispatch]

env:
  CONAN_USER_HOME: /home/conan

defaults:
  run:
    working-directory: /home/conan

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc11-ubuntu18.04
    env:
      CONAN_USER_HOME: /home/conan
      CONAN_SYSREQUIRES_MODE: enabled
      CONAN_PRINT_RUN_COMMANDS: 1
    steps:

      - name: Check out repository code
        uses: rodrigorodriguescosta/checkout@1d64c0a4a695ff5edb95596c11b430050668c83f  # FIXME: Not using actions/checkout just because of 'https://github.com/actions/checkout/pull/388'
        with:
          path: /home/conan

      - name: Configure Conan
        run: |
          pip install conan --upgrade
          conan --version
          conan profile detect          
          conan remote add default-conan-local https://carloszoido.jfrog.io/artifactory/api/conan/default-conan-local
          conan remote login default-conan-local ${{ secrets.RT_USERNAME }} -p=${{ secrets.RT_TOKEN }}
      - name: Build the package and run test_package
        run: |
          conan create . --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True -o opencv/*:with_ffmpeg=False -o opencv/*:with_gtk=False
          conan upload "*" -r=default-conan-local --all -c
      - name: Build the project locally
        run: |
          mkdir build
          cd build
          conan install .. -s build_type=Release --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True -o opencv/*:with_ffmpeg=False -o opencv/*:with_gtk=False
          cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/tests/build/Release/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
          make
          ./tflite-example mobilenet_v1_1.0_224_quant.tflite labels_mobilenet_quant_v1_224.txt frog.png 0
